### ISSUE TITLE
Find a new owner

### ISSUE THREAD

**Issue by haacked** [mateusrodrigues/letmebingthatforyou#2]
I really don't have the time to maintain this. I'm inclined to shut it down, but I'm happy to transfer it to someone else who'd rather take the reigns. Just reply to this issue.

**Comment by hoffarthaustin** [comment]
Ill take it

**Comment by mateusrodrigues** [comment]
I'm interested! Is it still up for grabs?

**Comment by ghost** [comment]
I’ve been following this since you posted. I did some thinking and I think I would love to take the owner position. I’ll put you in the credits as the founder. And I’ll have this site running within 2 days.

**Comment by haacked** [comment]
@mateusrodrigues Yes! Sorry for the very very late response. I'm happy to transfer this to you if you're still up for taking it over.

**Comment by mateusrodrigues** [comment]
@Haacked Yes, I'm still interested. Thank you!

**Comment by haacked** [comment]
I sent a transfer request to you.

**Comment by mateusrodrigues** [comment]
Got it, thank you! 😄

**Comment by haacked** [comment]
@mateusrodrigues I also own the domain name letmebingthatforyou.com. I should probably transfer that over to you as well once you get the site hosted and running somewhere.

**Comment by mateusrodrigues** [comment]
@Haacked email me at mateus(at)mateus.tech so that we can talk about the transfer
