### ISSUE TITLE
Website is down 

### ISSUE THREAD

**Issue by antequ** [mateusrodrigues/letmebingthatforyou#4]
Hi!

What is the status on the website? Is it still being maintained?

Thanks!

**Comment by haacked** [comment]
No it's not. I've been meaning to pass it on to someone who would like to take it over.

**Comment by antequ** [comment]
Got it! I just made a post on a Microsoft employees social Fb group to see if anyone wants to take it over in their spare time.

**Comment by arcadiogarcia** [comment]
I'm interested! DM'ed you on Twitter

**Comment by haacked** [comment]
Oh wait, I already handed this off to @mateusrodrigues. Sorry, I totally forgot about that. @mateusrodrigues, do you still plan to work on this?

**Comment by haacked** [comment]
I still own the domain name. once the site is up and running, I'll transfer over the domain name.

**Comment by mateusrodrigues** [comment]
Hi everyone!

@haacked yes, I've been improving the design and ported the project to .NET Core. I'll spin this up on an Azure Web App and let you know

**Comment by haacked** [comment]
@mateusrodrigues nice! Can't wait to see it.

**Comment by mateusrodrigues** [comment]
The website is live at [letmebingthatforyou.azurewebsites.net](https://letmebingthatforyou.azurewebsites.net). We're in the process of setting up the actual domain (letmebingthatforyou.com).

Also, there is a bit of latency from TinyURL's API when you request a link. I'm open to suggestions on this front :)

**Comment by mateusrodrigues** [comment]
Website is back live at [letmebingthatforyou.com](https://letmebingthatforyou.com)
